In [1]:
import pandas
import os
thisdir = '/home/idies/workspace/Storage/raddick/nba/'

datadir = '/home/idies/workspace/Temporary/raddick/nba_scratch/'
print('ok')

ok

In [8]:
#players_df = pandas.read_csv(datadir+'players.csv', encoding='utf-8', low_memory=False, index_col='playerID')
##players_df[players_df['name_last'] == 'Harden']#.groupby('playerID').size().sort_values(ascending=False).sort_index()
# James Harden playerID: hardeja01

#os.listdir(datadir)

#df1 = pandas.read_csv(datadir+'game_logs_2009_2010a.csv')
#df2 = pandas.read_csv(datadir+'game_logs_2009_2010b.csv')
#df3 = pandas.read_csv(datadir+'game_logs_2009_2010c.csv')
#df = pandas.concat((df1,df2,df3), axis=0)
#df = df.set_index(['playerID','gameID'])


#df.groupby('playerID')['pts'].sum()[df.groupby('playerID')['pts'].sum().index == 'hardeja01']

all_games_meta_df = pandas.DataFrame()
all_game_logs_df = pandas.DataFrame()

for i in range(2009, 2019):
    for j in ['a', 'b', 'c']:
        logs_df = pandas.read_csv(datadir+'game_logs_{0:.0f}_{1:.0f}{2:}.csv'.format(i, i+1, j), low_memory=False)
        #meta_df = pandas.read_csv(datadir+'games_meta_{0:.0f}_{1:.0f}{2:}.csv'.format(i, i+1, j), low_memory=False)
        #df = pandas.read_csv(datadir+'game_logs_{0:.0f}_{1:.0f}{2:}.csv'.format(i, i+1, j), low_memory=False)
        all_game_logs_df = pandas.concat((all_game_logs_df, logs_df), axis=0)
        #all_games_meta_df = pandas.concat((all_game_logs_df, meta_df), axis=0)
        
all_game_logs_df

,gameID,playerID,mp,fg,fga,fg3,fg3a,ft,fta,orb,...,trb,ast,stl,blk,tov,pf,pts,plus_minus,vis_or_home,starter
0,20091028ATL,murphtr01,1900-01-01 00:15:27,0,2,0,1,0,0,0,...,6,3,0,0,2,1,0,-14,0,True
1,20091028ATL,grangda01,1900-01-01 00:16:28,3,6,2,4,1,3,0,...,2,0,0,1,1,1,9,-16,0,True
2,20091028ATL,hibbero01,1900-01-01 00:10:20,1,4,0,0,0,0,1,...,2,1,0,1,2,1,2,-15,0,True
3,20091028ATL,fordtj01,1900-01-01 00:07:21,0,4,0,1,0,0,0,...,0,0,0,0,0,1,0,-8,0,True
4,20091028ATL,rushbr01,1900-01-01 00:04:37,1,1,0,0,0,0,0,...,0,0,0,0,0,1,2,-7,0,True
5,20091028ATL,jonesda02,1900-01-01 00:14:39,2,4,0,0,4,4,0,...,1,0,0,0,3,3,8,-5,0,False
6,20091028ATL,watsoea01,1900-01-01 00:16:39,4,5,2,2,3,4,0,...,1,1,0,0,2,3,13,-2,0,False
7,20091028ATL,jonesso01,1900-01-01 00:09:39,1,3,0,0,0,0,1,...,3,0,0,2,0,0,2,6,0,False
8,20091028ATL,headlu01,1900-01-01 00:12:16,3,6,0,1,0,0,0,...,1,1,0,0,1,1,6,8,0,False
9,20091028ATL,fosteje01,1900-01-01 00:12:34,0,0,0,0,2,2,0,...,3,2,0,0,0,3,2,3,0,False
10,20091028ATL,johnsjo02,1900-01-01 00:19:30,7,12,2,4,1,2,0,...,0,2,2,0,1,2,17,15,1,True
11,20091028ATL,smithjo03,1900-01-01 00:18:02,0,2,0,0,2,4,0,...,2,2,2,1,1,2,2,17,1,True
12,20091028ATL,horfoal01,1900-01-01 00:17:44,6,10,0,0,0,1,2,...,10,3,0,2,1,3,12,16,1,True
13,20091028ATL,willima02,1900-01-01 00:15:27,1,2,0,0,3,4,0,...,4,0,0,1,1,2,5,14,1,True
14,20091028ATL,bibbymi01,1900-01-01 00:14:19,3,5,2,3,0,0,0,...,3,2,2,0,2,0,8,15,1,True
15,20091028ATL,pachuza01,1900-01-01 00:08:16,0,1,0,0,0,2,0,...,0,0,0,0,0,0,0,-9,1,False
16,20091028ATL,evansma01,1900-01-01 00:07:32,2,3,0,0,3,3,1,...,1,0,0,0,0,1,7,-6,1,False
17,20091028ATL,teaguje01,1900-01-01 00:07:06,0,3,0,0,0,0,1,...,2,2,0,0,0,2,0,-6,1,False
18,20091028ATL,crawfja01,1900-01-01 00:08:06,1,2,0,0,1,1,0,...,0,2,0,0,0,2,3,-2,1,False
19,20091028ATL,smithjo02,1900-01-01 00:03:58,0,1,0,0,0,0,1,...,1,0,0,0,0,1,0,-4,1,False
20,20091030ATL,arenagi01,1900-01-01 00:18:40,6,13,1,3,1,2,1,...,1,1,0,0,1,0,14,1,0,True
21,20091030ATL,haywobr01,1900-01-01 00:13:55,1,3,0,0,5,6,2,...,6,0,0,1,0,1,7,4,0,True
22,20091030ATL,millemi01,1900-01-01 00:24:00,3,4,0,0,0,0,0,...,5,2,0,0,2,2,6,3,0,True
23,20091030ATL,obertfa01,1900-01-01 00:07:09,1,1,0,0,0,0,0,...,2,0,0,0,0,0,2,2,0,True
24,20091030ATL,blatcan01,1900-01-01 00:16:51,1,1,0,0,2,4,0,...,4,0,0,0,1,2,4,1,0,False
25,20091030ATL,foyera01,1900-01-01 00:17:27,1,9,1,2,2,2,0,...,2,4,0,0,0,0,5,8,0,False
26,20091030ATL,youngni01,1900-01-01 00:04:22,0,4,0,2,0,0,0,...,0,0,0,0,0,1,0,-1,0,False
27,20091030ATL,stevede01,1900-01-01 00:07:31,0,0,0,0,0,0,0,...,1,0,0,0,0,1,0,-2,0,False
28,20091030ATL,mcgeeja01,1900-01-01 00:10:05,3,4,0,0,1,2,1,...,2,1,0,2,0,2,7,-1,0,False
29,20091030ATL,horfoal01,1900-01-01 00:22:22,2,5,0,0,0,0,3,...,6,0,0,4,0,2,4,-2,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8191,20190405WAS,motiedo01,1900-01-01 00:04:21,1,4,0,0,0,0,1,...,1,0,0,1,1,1,2,-6,0,False
8192,20190405WAS,pondequ01,1900-01-01 00:04:21,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,-6,0,False
8193,20190405WAS,eubandr01,1900-01-01 00:03:48,1,1,0,0,0,0,1,...,1,0,0,1,1,0,2,-6,0,False
8194,20190405WAS,portibo01,1900-01-01 00:18:02,2,6,1,4,2,2,0,...,3,1,0,0,1,1,7,9,1,True
8195,20190405WAS,browntr01,1900-01-01 00:20:13,1,6,0,2,2,2,1,...,3,1,0,0,0,0,4,4,1,True
8196,20190405WAS,bryanth01,1900-01-01 00:15:57,3,5,0,2,0,0,2,...,6,0,0,0,1,1,6,-5,1,True
8197,20190405WAS,bealbr01,1900-01-01 00:12:00,5,8,2,5,3,3,0,...,1,1,0,0,0,0,15,2,1,True
8198,20190405WAS,satorto01,1900-01-01 00:09:59,0,3,0,1,2,2,0,...,0,1,0,0,0,2,2,2,1,True
8199,20190405WAS,greenje02,1900-01-01 00:09:40,3,4,0,0,2,2,0,...,1,0,0,1,0,0,8,-6,1,False
8200,20190405WAS,randlch01,1900-01-01 00:12:00,1,3,1,2,2,3,0,...,1,1,1,0,0,0,5,0,1,False
8201,20190405WAS,mcraejo01,1900-01-01 00:03:47,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,-2,1,False
8202,20190405WAS,robinde01,1900-01-01 00:14:01,1,2,0,0,2,2,1,...,5,1,0,2,0,3,4,0,1,False
8203,20190405WAS,dekkesa01,1900-01-01 00:04:21,1,2,1,1,0,0,0,...,0,0,0,0,0,0,3,6,1,False
8204,20190409WAS,ojelese01,1900-01-01 00:20:33,4,11,1,5,0,2,2,...,3,1,1,0,0,1,9,7,0,True
8205,20190409WAS,williro04,1900-01-01 00:12:06,0,1,0,0,0,0,0,...,5,1,0,2,1,2,0,17,0,True
8206,20190409WAS,yabusgu01,1900-01-01 00:11:47,3,4,2,2,0,2,1,...,2,1,0,0,0,0,8,-10,0,True
8207,20190409WAS,roziete01,1900-01-01 00:08:49,2,5,1,3,1,2,0,...,1,1,1,0,0,0,6,-9,0,True
8208,20190409WAS,brownja02,1900-01-01 00:03:45,1,3,0,1,1,2,0,...,0,0,1,0,1,1,3,-12,0,True
8209,20190409WAS,doziepj01,1900-01-01 00:23:11,3,7,1,3,1,2,4,...,9,0,1,0,0,1,8,7,0,False
8210,20190409WAS,wanambr01,1900-01-01 00:18:38,2,7,0,2,4,6,0,...,4,5,0,0,0,0,8,16,0,False
8211,20190409WAS,hunterj01,1900-01-01 00:15:11,4,9,2,6,1,2,1,...,3,2,1,0,0,1,11,16,0,False
8212,20190409WAS,theisda01,1900-01-01 00:06:00,0,0,0,0,0,0,1,...,2,0,0,0,0,1,0,3,0,False
8213,20190409WAS,satorto01,1900-01-01 00:12:00,4,5,2,2,2,2,0,...,2,0,0,0,2,1,12,5,1,True
8214,20190409WAS,portibo01,1900-01-01 00:08:28,1,4,0,1,0,0,1,...,3,3,0,0,1,1,2,7,1,True
8215,20190409WAS,bryanth01,1900-01-01 00:08:28,2,3,0,1,1,1,0,...,4,2,0,0,1,1,5,7,1,True
8216,20190409WAS,dekkesa01,1900-01-01 00:15:32,1,4,1,2,0,0,1,...,2,0,0,0,0,2,3,-14,1,False
8217,20190409WAS,robinde01,1900-01-01 00:20:28,4,7,0,1,0,0,2,...,4,1,0,1,1,2,8,-5,1,False
8218,20190409WAS,randlch01,1900-01-01 00:15:32,1,4,1,3,2,2,0,...,0,2,0,0,1,2,5,-14,1,False
8219,20190409WAS,mahinia01,1900-01-01 00:15:32,2,9,1,2,0,0,4,...,10,1,1,1,1,3,5,-14,1,False
8220,20190409WAS,greenje02,1900-01-01 00:24:00,2,13,1,8,1,2,0,...,5,3,0,1,2,0,6,-7,1,False

In [ ]:
.